title: GITHUB PORTFOLIO
description: Christian Gabriel Centeno
github: false
show_downloads: false
google_analytics: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
include:
  - assets/img/favicon.png
